#!/bin/bash
# 编译脚本成二进制文件
#   "name": "bud2exe",
#   "version": "1.0.0",
#   "description": "一个sh脚本编译工具,可以编译脚本成bin或exe文件,暂时不支持MacOS,可绕过杀软,请不要编译非法代码.Tg讨论组:https://t.me/+BqvlH6BDOWE3NjQ1,赞助我们:TKqTUNcBWiRDdczuHoQstMD4XRyFgNwHiF (TRX/USDT)\",
#   "main": "Src/bud2exe",
#   "author": "aspnmy@gmail.com",
#   "license": "ISC",
#   "bugs": {
#     "url": "https://github.com/aspnmy/bud2exe/issues"
#   },
#   "homepage": "https://github.com/aspnmy/bud2exe#readme"

BUDTOOL_VER="1.0.0"
SH_NAME="poetryBeBe"
SRC_DIR="../Src"
BUD_DIR="../build"
BUD_VER=$(cat ${SRC_DIR}/newVer.bud)

bud2bin(){
    mkdir -p ${BUD_DIR}/${BUD_VER}
    shc -f ${SRC_DIR}/${SH_NAME} -o ${BUD_DIR}/${BUD_VER}${SH_NAME}
    echo "脚本编译成功,保存在'${BUD_DIR}/${BUD_VER}${SH_NAME}'"
    exit
}

bud2exe(){
    mkdir -p ${BUD_DIR}/${BUD_VER}

    #shc -f ${SRC_DIR}/${SH_NAME} -o ${BUD_DIR}/${BUD_VER}${SH_NAME}
    echo "编译教程成exe文件,正在开发中......"
    #echo "脚本编译成功,保存在'${BUD_DIR}/${BUD_VER}${SH_NAME}'"
    exit
}

# 定义一个函数来显示菜单
show_menu(){
    echo "poetryBeBe poetry哔哔小子,一个简单的poetry管理工具-免费版"
    echo "Tg讨论组:https://t.me/+BqvlH6BDOWE3NjQ1"
    echo "赞助我们:TKqTUNcBWiRDdczuHoQstMD4XRyFgNwHiF (TRX/USDT)"
    echo "请选择一个-选项:"
    echo "1)bud2bin/编译脚本成为一个二进制文件(需要sfc组件)"
    echo "2)bud2exe/编译脚本成为一个exe文件(需要c安装器)"
    echo "0)退出"
}

# 无限循环,直到用户选择退出
while true; do
    show_menu
    read -p "请输入你的选择: " choice

    # 根据用户的选择执行不同的操作
    case $choice in
        1)
            echo "你选择了-bud2bin/编译脚本成为一个二进制文件(需要sfc组件:sudo apt-get install -y sfc)"
            bud2bin
            ;;
        2)
            echo "你选择了-bud2exe/编译脚本成为一个exe文件(需要c安装器)"
            bud2exe
            ;;
        0)
            echo "退出菜单"
            break
            ;;            
        *)
            echo "无效的-选项,请重新输入。"
            ;;
    esac
    echo "" # 打印一个空行以分隔菜单
done