#!/bin/bash
# 读取版本号
bud_ver=$(cat "./newVer.bud")
if [ -z "$bud_ver" ]; then
    echo "Error: Version file './newVer.bud' is empty or found."
    exit 1
fi

budpBB(){
    ./bud2exe-cli-v1.0.0 -s b2bin -o "../Build/bud2exe_pBB_sfh_linux" -f "./bud2exe-poetryBeBe"
    ./bud2exe-cli-v1.0.0 -s b2GCC -o "../Build/bud2exe_pBB_gcc_linux" -f "./bud2exe-poetryBeBe"
    sha256sum "../Build/bud2exe_pBB_sfh_linux_v$bud_ver" > "../Build/bud2exe_pBB_sfh_linux_v$bud_ver.sha256"
    sha256sum "../Build/bud2exe_pBB_gcc_linux_v$bud_ver" > "../Build/bud2exe_pBB_gcc_linux_v$bud_ver.sha256"

}

bud2cli(){
    ./bud2exe-cli-v1.0.0 -s b2bin -o "../Build/bud2exe-cli_sfh_linux" -f "./bud2exe-cli-v1.0.0"
    ./bud2exe-cli-v1.0.0 -s b2GCC -o "../Build/bud2exe-cli_gcc_linux" -f "./bud2exe-cli-v1.0.0"
    sha256sum "../Build/bud2exe-cli_sfh_linux_v$bud_ver" > "../Build/bud2exe-cli_sfh_linux_v$bud_ver.sha256"
    sha256sum "../Build/bud2exe-cli_gcc_linux_v$bud_ver" > "../Build/bud2exe-cli_gcc_linux_v$bud_ver.sha256"

}

main(){
    budpBB
    bud2cli
}

main